---
title: "playground"
author: "Dan Weinberger"
date: "2023-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library(readr)
library(MASS)
library(rio)
library(readxl)
library(htmlTable)
library(arules)
library(dplyr)
library(arulesViz)
library(gridExtra)
library(ggplot2)
library(abind)
library(ggrepel)
```

## R Markdown

GPS
```{r}
gps1<-read_csv('./Data/monocle-metadata-gps_2023-08-04.csv',guess_max=10000)
gps1<-gps1[,c('In_silico_serotype', 'GPSC')]
names(gps1)<-c('st','SC')
gps1$count<-1
gps1$st[gps1$st=='15BC']<-'15B/C'
gps1.m<-melt(gps1, id.vars=c('st','SC'))
gps1.c<- dcast(gps1.m,st~SC,fun.aggregate = sum )
```


```{r}

ps1<-import('https://raw.githubusercontent.com/weinbergerlab/GrowthVariation/master/Data/PS%20Composition_SS_final.csv')
ps1$Ribitol<-ps1$`Rib-ol`
ps1$Serotype[ps1$Serotype=='15B']<-'15B/C'
ps1$any.nac<-apply(ps1[,c('FucNAc','GalNAc', 'ManNAc', 'ManNAcA','PneNAc', 'GlcNAc')], 1,sum)
ps1$any.nac<-(ps1$any.nac>0)*1

ps1 <- ps1 %>%
  mutate(
         Gal = ifelse(Serotype=='23A', 1, Gal) ,  #https://pubmed.ncbi.nlm.nih.gov/28837839
         Rha = ifelse(Serotype=='23A', 1, Rha) ,  #https://pubmed.ncbi.nlm.nih.gov/28837839
         Gro = ifelse(Serotype=='23A', 1, Gro) ,  #https://pubmed.ncbi.nlm.nih.gov/28837839
               
         Rha = ifelse(Serotype=='7C', 1, Rha) ,  #https://pubmed.ncbi.nlm.nih.gov/29715685/
         any.nac = ifelse(Serotype=='7C', 1, any.nac)   #https://pubmed.ncbi.nlm.nih.gov/29715685/
         
  ) %>%
  rename(st=Serotype)
```

```{r}
d1 <- gps1 %>%
  left_join(ps1, by='st') %>%
  group_by(SC) %>%
  summarize( rha_prop=mean(Rha, na.rm=T), any.nac.prop=mean(any.nac, na.rm=T), n_isolates=n(), n_serotypes=n_distinct(st), serotypes=paste(unique(st), collapse='_')) %>%
  filter(n_serotypes>=3 & n_isolates>=50) %>%
  arrange(-rha_prop)


write.csv(d1,'./Data/st_gps_combos.csv')

hist(d1$rha_prop)
hist(d1$any.nac.prop)

```


